# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./services/FileSystemHandler.h \
    ./shared/net/packets/Packet.h \
    ./shared/net/packets/PacketDesktopRequest.h \
    ./shared/net/packets/PacketDesktopResponse.h \
    ./shared/net/packets/PacketLoginRequest.h \
    ./shared/net/packets/PacketLoginResponse.h \
    ./shared/net/packets/PacketPresentation.h \
    ./shared/net/packets/PacketShellResponse.h \
    ./shared/net/packets/PacketType.h \
    ./services/SystemHandler.h \
    ./services/DesktopHandler.h \
    ./services/NetService.h \
    ./XeytanQppClient.h \
    ./ui/qt/mainwindow.h
SOURCES += ./services/DesktopHandler.cpp \
    ./services/FileSystemHandler.cpp \
    ./services/NetService.cpp \
    ./shared/net/packets/Packet.cpp \
    ./shared/net/packets/PacketDesktopRequest.cpp \
    ./shared/net/packets/PacketDesktopResponse.cpp \
    ./shared/net/packets/PacketLoginRequest.cpp \
    ./shared/net/packets/PacketLoginResponse.cpp \
    ./shared/net/packets/PacketPresentation.cpp \
    ./shared/net/packets/PacketShellResponse.cpp \
    ./utils/QtHelpers.cpp \
    ./services/SystemHandler.cpp \
    ./XeytanQppClient.cpp \
    ./main.cpp \
    ./ui/qt/mainwindow.cpp
FORMS += ./ui/qt/mainwindow.ui
